pybo/views/api_request_views.py
import json
from datetime import datetime
from sqlalchemy import func

from urllib.request import urlopen
from urllib.parse import quote

from bs4 import BeautifulSoup

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Apireq, Apires, User
from pybo.forms import ApireqForm
from pybo.views.auth_views import login_required

bp = Blueprint('api_request', __name__, url_prefix='/api/request')

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    so = request.args.get('so', type=str, default='recent')

    # 추천 교차 테이블 내 게시글 별 카운트 처리.
    if so == 'popular':
        sub_query = db.session.query(Apires.apireq_id, func.count('*').label('num_apires')) \
            .group_by(Apires.apireq_id).subquery()
        apireq_list = Apireq.query \
            .outerjoin(sub_query, Apireq.id == sub_query.c.apireq_id) \
            .order_by(sub_query.c.num_apires.desc(), Apireq.create_date.desc())
    else:  # recent
        apireq_list = Apireq.query \
            .order_by(Apireq.create_date.desc())

    if kw:
        search = '%%{}%%'.format(kw)
        apireq_list = apireq_list \
            .join(User) \
            .filter(Apireq.subject.ilike(search) |  # 질문제목
                    User.username.ilike(search)   # 질문작성자
                    ) \
            .distinct()
    print("QUERY[_list] :: ", apireq_list)
    #페이징
    apireq_list = apireq_list.paginate(page, per_page=10)

    return render_template('api/request/list.html', apireq_list=apireq_list, page=page, kw=kw, so=so)

@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = ApireqForm()
    if request.method == 'POST' and form.validate_on_submit():
        apireq = Apireq(subject=form.subject.data,
                  service_key=form.service_key.data,
                  target_url=form.target_url.data,
                  parameter=form.parameter.data,
                  data_type='XML',
                  create_date=datetime.now(),
                  user=g.user)
        db.session.add(apireq)
        db.session.commit()
        return redirect(url_for('api_request._list'))

    return render_template('api/request/form.html', form=form)


@bp.route('/detail/<int:apireq_id>/')
def detail(apireq_id):
    page = request.args.get('page', type=int, default=1)

    # 조회
    apireq = Apireq.query.get_or_404(apireq_id)

    # 결과 조회
    apires_list = Apires.query \
        .filter_by(apireq=apireq) \
        .order_by(Apires.create_date.desc())

    apires_list = apires_list.paginate(page, per_page=5)

    return render_template('api/request/detail.html', apireq=apireq, apires_list=apires_list, page=page)

@bp.route('/modify/<int:apireq_id>', methods=('GET', 'POST'))
@login_required
def modify(apireq_id):
    apireq = Apireq.query.get_or_404(apireq_id)
    if g.user != apireq.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('api_request.detail', apireq_id=apireq_id))
    if request.method == 'POST':
        form = ApireqForm()
        if form.validate_on_submit():
            form.populate_obj(apireq)
            apireq.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('api_request.detail', apireq_id=apireq_id))
    else:
        form = ApireqForm(obj=apireq)

    return render_template('api/request/form.html', form=form)

@bp.route('/delete/<int:apireq_id>')
@login_required
def delete(apireq_id):
    apireq = Apireq.query.get_or_404(apireq_id)
    if g.user != apireq.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('api_request.detail', apireq_id=apireq_id))
    db.session.delete(apireq)
    db.session.commit()
    return redirect(url_for('api_request._list'))

@bp.route('/call/<int:apireq_id>')
def call(apireq_id):
    # 조회
    apireq = Apireq.query.get_or_404(apireq_id)

    target_url = apireq.target_url + "?ServiceKey=" + apireq.service_key
    parameter = apireq.parameter
    jsonObject = json.loads(parameter)

    for key in jsonObject:
        target_url = target_url + "&" + key + "=" + quote(jsonObject.get(key))

    result_data = urlopen(target_url).read().decode('utf-8')

    #soup = BeautifulSoup(result_data, 'html.parser')
    #items = soup.findAll('item')
    #for item in items:
    #    print("CTIY NAME == ", item.find('cityname').string)
    #    print("PM10 == ", item.find('pm10value').string)

    #저장처리 부
    apires = Apires(parameter=apireq.parameter,
                    data_type=apireq.data_type,
                    result_data=result_data,
                    create_date=datetime.now(),
                    user=g.user)
    apireq.apires_set.append(apires)
    db.session.commit()

    return redirect(url_for('api_request.detail', apireq_id=apireq_id))

pybo/templates/api/request/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-sm-12 col-md-9 col-lg-10 p-2">
    <div class="container my-3">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        <h2 class="border-bottom py-2">{{ apireq.subject }}</h2>
        <div class="row my-3">
            <div class="col-12"> <!-- 질문영역 -->
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="subject">제목</label>
                            <input type="text" class="form-control" name="subject" id="subject" readonly
                                value="{{ apireq.subject or '' }}">
                        </div>
                        <div class="form-group">
                            <label for="service_key">서비스키</label>
                            <input type="text" class="form-control" name="service_key" id="service_key" readonly
                                value="{{ apireq.service_key or '' }}">
                        </div>
                        <div class="form-group">
                            <label for="target_url">URL</label>
                            <input type="text" class="form-control" name="target_url" id="target_url" readonly
                                value="{{ apireq.target_url or '' }}">
                        </div>
                        <div class="form-group">
                            <label for="parameter">파라미터</label>
                            <textarea class="form-control" name="parameter" id="parameter" readonly rows="5">{{ apireq.parameter or '' }}</textarea>
                        </div>
                        <div class="d-flex justify-content-end">
                            {% if apireq.modify_date %}
                            <div class="badge badge-light p-2 text-left mx-3">
                                <div class="mb-2">modified at</div>
                                <div>{{ apireq.modify_date|datetime }}</div>
                            </div>
                            {% endif %}
                            <div class="badge badge-light p-2 text-left">
                                <div class="mb-2">{{ apireq.user.username }}</div>
                                <div>{{ apireq.create_date|datetime }}</div>
                            </div>
                        </div>
                        <div class="my-3">
                            <a href="#" class="call btn btn-sm btn-outline-secondary"
                               data-uri="{{ url_for('api_request.call', apireq_id=apireq.id) }}">실행</a>
                            {% if g.user == apireq.user %}
                            <a href="{{ url_for('api_request.modify', apireq_id=apireq.id) }}"
                               class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="#" class="delete btn btn-sm btn-outline-secondary"
                               data-uri="{{ url_for('api_request.delete', apireq_id=apireq.id) }}">삭제</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 답변시작 -->
        <a name="apires_start"></a>
        <div class="d-flex justify-content-between border-top my-3 py-2">
            <h5>
                <strong>{{ apireq.apires_set|length }}</strong>개의 처리이력이 있습니다.
                <small class="ml-5">{{ apires_list.page }} / {{ apires_list.pages }} Page</small>
            </h5>
        </div>
        {% for apires in apires_list.items %}
        <a name="apires_{{ apires.id }}"></a>
        <div class="row my-3">
            <div class="col-12">  <!-- 답변영역 -->
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">{{ apires.result_data }}</div>
                        <div class="d-flex justify-content-end">
                            {% if apires.modify_date %}
                            <div class="badge badge-light p-2 text-left mx-3">
                                <div class="mb-2">modified at</div>
                                <div>{{ apires.modify_date|datetime }}</div>
                            </div>
                            {% endif %}
                            <div class="badge badge-light p-2 text-left">
                                <div class="mb-2">{{ apires.user.username }}</div>
                                <div>{{ apires.create_date|datetime }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <a href="{{ url_for('api_request._list') }}" class="btn btn-primary"><i class="bi bi-list-ul"></i> 목록으로</a>
        <ul class="pagination pagination-sm justify-content-center">
            <!-- 이전페이지 -->
            {% if apires_list.has_prev %}
            <li class="page-item">
                <a class="page-link" data-page="{{ apires_list.prev_num }}" href="#">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            {% for page_num in apires_list.iter_pages() %}
                {% if page_num %}
                    {% if page_num != apires_list.page %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                    </li>
                    {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li>
                    {% endif %}
                {% else %}
                    <li class="disabled">
                        <a class="page-link" href="#">...</a>
                    </li>
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if apires_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ apires_list.next_num }}" href="#">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <form id="searchForm" method="get" action="{{ url_for('api_request.detail', apireq_id=apireq.id) }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".call").on('click', function() {
        if(confirm("실행 하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

pybo/templates/api/request/form.html
{% extends 'base.html' %}
{% block content %}
<div class="col-sm-12 col-md-9 col-lg-10 p-2">
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">API 호출</h5>
        <form method="post" class="post-form my-3">
            {{ form.csrf_token }}
            {% for field, errors in form.errors.items() %}
            <div class="alert alert-danger" role="alert">
                <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
            </div>
            {% endfor %}
            <div class="form-group">
                <label for="subject">제목</label>
                <input type="text" class="form-control" name="subject" id="subject"
                    value="{{ form.subject.data or '' }}">
            </div>
            <div class="form-group">
                <label for="service_key">서비스키</label>
                <input type="text" class="form-control" name="service_key" id="service_key"
                    value="{{ form.service_key.data or '' }}">
            </div>
            <div class="form-group">
                <label for="target_url">URL</label>
                <input type="text" class="form-control" name="target_url" id="target_url"
                    value="{{ form.target_url.data or '' }}">
            </div>
            <div class="form-group">
                <label for="parameter">파라미터</label>
                <textarea class="form-control" name="parameter" id="parameter" rows="5">{{ form.parameter.data or '' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
</div>
{% endblock %}

pybo/templates/api/request/list.html
{% extends 'base.html' %}
{% block content %}
<div class="col-sm-12 col-md-9 col-lg-10 p-2">
    <h5><strong>API 목록</strong></h5>
    <div id="content" class="border-top">
        <div class="content_block">
            <div class="row justify-content-between my-3">  <!-- 양쪽정렬 justify-content-between로 변경 -->
                <div class="col-2">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-sm btn-secondary so {% if so=='recent' %}active{% endif %}" data-so="recent"  data-original-title="최신순">
                            <i class="bi bi-list-ul"></i>
                        </button>
                        <button type="button" class="btn btn-sm btn-secondary so {% if so=='popular' %}active{% endif %}" data-so="popular" data-original-title="활용순">
                            <i class="bi bi-suit-heart-fill"></i>
                        </button>
                    </div>
                </div>
                <div class="col-4 input-group">
                    <input type="text" class="form-control kw" value="{{ kw or '' }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                    </div>
                </div>
            </div>

            <table class="table">
                <thead>
                <tr class="thead-dark">
                    <th>번호</th>
                    <th style="width:50%">제목</th>
                    <th>생성자</th>
                    <th style="width:200px">작성일시</th>
                </tr>
                </thead>
                <tbody>
                {% if apireq_list %}
                {% for apireq in apireq_list.items %}
                <tr>
                    <td>{{ apireq_list.total - ((apireq_list.page-1) * apireq_list.per_page) - loop.index0 }}</td>
                    <td>
                        <a href="{{ url_for('api_request.detail', apireq_id=apireq.id) }}">{{ apireq.subject }}</a>
                        {% if apireq.answer_set|length > 0 %}
                        <span class="text-danger small ml-2">{{ apireq.answer_set|length }}</span>
                        {% endif %}
                    </td>
                    <td>{{ apireq.user.username }}</td>
                    <td>{{ apireq.create_date|datetime }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">데이터가 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if apireq_list.has_prev %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ apireq_list.prev_num }}" href="#">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                {% for page_num in apireq_list.iter_pages() %}
                    {% if page_num %}
                        {% if page_num != apireq_list.page %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                        </li>
                        {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{ page_num }}</a>
                        </li>
                        {% endif %}
                   {% else %}
                        <li class="disabled">
                            <a class="page-link" href="#">...</a>
                        </li>
                   {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if apireq_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ apireq_list.next_num }}"  href=#">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
            <a href="{{ url_for('api_request.create') }}" class="btn btn-primary"><i class="bi bi-pencil-fill"></i> 등록하기</a>
            <form id="searchForm" method="get" action="{{ url_for('api_request._list') }}">
                <input type="hidden" id="page" name="page" value="{{ page }}">
                <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
                <input type="hidden" id="so" name="so" value="{{ so }}">
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
    $(".so").on('click', function() {
        $("#so").val($(this).data("so"));
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}