pybo/views/auth_views.py
import os
from datetime import datetime
from PIL import Image
from flask import current_app, Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect, secure_filename

import functools
from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm, UserSettingsBaseForm
from pybo.models import User, Question

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),#generate_password_hash : 복호화 불가, 비교 시 암호화 후 처리.
                        email=form.email.data,
                        create_date=datetime.now())
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))#url_for : 라우트가 설정된 함수명으로 URL을 역으로 찾아준다.
        else:
            flash('이미 존재하는 상용자입니다.')#flash : 논리오류를 발생시킨다.

    return render_template('auth/signup.html', form=form)  #render_template : 템플릿 화면을 그려준다.

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS']

@bp.route('/settings/', methods=('GET', 'POST'))
def settings():
    ni = request.args.get('ni', type=str, default='base')
    user = User.query.get_or_404(g.user.id)

    if ni == 'base':
        if request.method == 'POST':
            form = UserSettingsBaseForm()
            if form.validate_on_submit():
                form.populate_obj(user)
                user.modify_date = datetime.now()  # 수정일시 저장
                db.session.commit()
                return redirect(url_for('main.index'))
        else:
            form = UserSettingsBaseForm(obj=user)
        return render_template('auth/settings_base.html', form=form, ni=ni)
    elif ni == 'image':
        if request.method == 'POST':
            file = request.files['profile_image']
            if file and allowed_file(file.filename):
                file_name = secure_filename(file.filename)
                file_path = os.path.join(current_app.config['UPLOAD_SV_DIR'], file_name)
                #이미지 리사이즈 처리
                img = Image.open(file)
                img_resize = img.resize((256, 256))
                img_resize.save(file_path)
                #파일경로 저장
                user.image_path = os.path.join(current_app.config['UPLOAD_DB_DIR'], file_name)
                db.session.commit()
                return redirect(url_for('main.index'))
        return render_template('auth/settings_image.html', ni=ni)

    return redirect(url_for('main.index'))

@bp.route('/profile/')
def profile():
    ni = request.args.get('ni', type=str, default='base')
    user = User.query.get_or_404(g.user.id)
    if ni == 'question':
        page = request.args.get('page', type=int, default=1)
        question_list = Question.query \
            .filter_by(user_id=g.user.id) \
            .order_by(Question.create_date.desc())
        question_list = question_list.paginate(page, per_page=5)
        return render_template('auth/profile_question.html', question_list=question_list, user=user, ni=ni)

    return render_template('auth/profile_base.html', user=user, ni=ni)

@bp.before_app_request #before_app_request : 라우트함수보타 먼저 실행
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None #g : 플라스크가 제공하는 컨텍스트 변수
    else:
        g.user = User.query.get(user_id)

#데코레이션 함수
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

pybo/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>PYBO</title>
    {{ simplemde.css }}
    {{ simplemde.js }}
</head>
<body>
{% include "navbar.html" %}
<div class="container mt-3">
    <div class="row">
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{{ url_for('static', filename='jquery-3.5.1.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
    </div>
</div>
</body>
</html>

pybo/templates/category.html
{% if menu_list %}
    <div class="col-sm-12 col-md-3 col-lg-2 p-2">
        <!-- Sidebar  -->
        <nav id="sidebar" class="border-top">
            <div class="list-group">
                {% for menu_item in menu_list %}
                    {% if menu_item.id == menu.id %}
                    <a class="rounded-0 list-group-item list-group-item-action list-group-item-light active" href="{{ url_for('question._list', menu_id=menu_item.id) }}">{{ menu_item.title }}</a>
                    {% else %}
                    <a class="rounded-0 list-group-item list-group-item-action list-group-item-light" href="{{ url_for('question._list', menu_id=menu_item.id) }}">{{ menu_item.title }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </nav>
    </div>
{% endif %}

pybo/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pybo/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('question._list') }}">
                    <i class="bi bi-chat-dots-fill"></i> 질문 목록
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('api_request._list') }}">
                    <i class="bi bi-binoculars-fill"></i> API 목록
                </a>
            </li>
            {% if g.user %}
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.settings') }}">
                       <i class="bi bi-gear-fill"></i> 계정설정</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.profile') }}">
                        <i class="bi bi-person-fill"></i> {{ g.user.username }}</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">
                        <i class="bi bi-box-arrow-right"></i> 로그아웃</a>
                </li>
            {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">
                        <i class="bi bi-person-plus-fill"></i> 계정생성
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">
                        <i class="bi bi-box-arrow-in-right"></i> 로그인
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>